[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$w9ibM6Y0xnjvXYsRIuT8Hw$8qf3ihMMJBs4y6u6NOlhXRJAbS1bwLzfAEIYNf22bpNrQZqTxYki9tJYe4PR246Fnfr6wXeu6deGvENnTepHLQ

