[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$oTQGAMBY690bQwiB0JrTug$aTLGtkXc3wn/q4jG6N1LJeHDhuSM0NSkWGLB5RTomoN423RqUHo6Ks6E81W/Xm6g0QvVEd75DlvHBP5jL8LIUA

