[options]
; Database
db_host = db
db_port = 5432
db_user = odoo
db_password = !password123

; Addons
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons,/var/lib/odoo/.local/share/Odoo/addons/19.0
